version: '3'
services:
  mymongodb:
    image: wrathofthetyrant/mongo
    build: ./mongodb
    container_name: mymongodb
    ports:
        - '27017:27017'
    volumes:
      - ./mongodb/data:/data/db
  favourites:
    container_name: favourites
    build: ./backend/favourites
    image: wrathofthetyrant/reactreduxresfulmaps_favourites
    volumes:
      - ./backend/favourites:/code
    ports:
      - "5000:5000"
    links:
      - mymongodb
    depends_on:
      - mymongodb
  mytrips:
    container_name: mytrips
    build: ./backend/my_trips
    image: wrathofthetyrant/reactreduxresfulmaps_my_trips 
    volumes:
      - ./backend/my_trips:/code
    ports:
      - "5001:5001"
    links:
      - mymongodb
    depends_on:
      - mymongodb
  frontend:
    container_name: frontend_holidaytracker
    build: ./frontend
    image: wrathofthetyrant/reactreduxresfulmaps_frontend 
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"
    links:
      - favourites
      - mytrips
    depends_on:
      - favourites
      - mytrips
