version: '3'
services:
  my_mongodb:
    image: wrathofthetyrant/mongo
    build: ./mongodb
    container_name: my_mongodb
    ports:
        - '27017:27017'
    volumes:
      - ./mongodb/data:/data/db
  favourites:
    container_name: favouritesdb
    build: ./backend/favourites
    image: wrathofthetyrant/reactreduxresfulmaps_favourites
    volumes:
      - ./backend/favourites:/code
    ports:
      - "5000:5000"
    links:
      - my_mongodb
    depends_on:
      - my_mongodb
  my_trips:
    container_name: my_tripsdb
    build: ./backend/my_trips
    image: wrathofthetyrant/reactreduxresfulmaps_my_trips 
    volumes:
      - ./backend/my_trips:/code
    ports:
      - "5001:5001"
    links:
      - my_mongodb
    depends_on:
      - my_mongodb
  frontend:
    container_name: frontend_holidaytracker
    build: ./frontend
    image: wrathofthetyrant/reactreduxresfulmaps_frontend 
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"
    links:
      - favourites
      - my_trips
    depends_on:
      - favourites
      - my_trips
