# version: "3"
# services:
#   favourites:
#     container_name: favouritesdb
#     build: ./backend/favourites
#     ports:
#     - "5000:5000"
#     depends_on:
#     - mongo
#   mongo:
#     image: mongo
#     ports:
#     - "27017:27017"


version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
        - '27017:27017'
    volumes:
      - ./mongodb/data:/data/db
  favourites:
    container_name: favouritedb
    build: ./backend/favourites
    volumes:
      - ./backend/favourites:/code
    ports:
      - "5000:5000"
    links:
      - mongodb
    depends_on:
      - mongodb
